language: node_js
node_js:
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "dK7lezEWj6zlTIQ+DywtNNdGwthyYEp4Axl5o6x3JaEvIBmpx846523tn1N5aXomcghVWwyjZcu0zIJgELyzhQT6ogXSijG7PBrCOvebuhIFz/xC7qS+OW5DXdQ/tlU1Kv9peC+hoyv3ANvHPhspd0TpCRHFJZ2+W2WY8rhWSM9S/GqG8BQnD3gfIQATB/K613CtMkMHH/n0lI4CxNImxo+YUsLALmDWiC3baBHklpUsg1Q7Uv2subJhK5PO66btL6aUtLv8XGFaMU6xbezib6y2e8YR6LUiXK1/yXGa3joiD7gANT0IY6hnrp+dqxcnAhFhnoCKNY0Sf/DTcwrCa3w8sIkV5fc7KgGD9OEi9hL/7hvV4w5MRREi10aMXPTAaRFj+R4zfMxNHqKdDS3Z/mT92i3zSHOE5BrTe7AYp1fxrmsOuSZDnfmwFmtEwm7p20d1gv1uUunJIsxnJigkhef+bjdvHs4nf4KRs7Njm2V9ZGjRDpEoVJ4/LKrtJQM9eL3KvOAQarCpLdgN/8hMqTD2JupBk/LXAy6NVINAnfehOFuhNE0kkDOYy73Bx2bIrbrpqUf5s64ZofhmmMreR/Ej0QUiLTJNyiG23vq0H7Y/mi8sMH4i38VAwYjXVEvudA2fflB2aRDNuYWSj420nD/Dl/AGpGdwPR+7flRLNkE="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "dK7lezEWj6zlTIQ+DywtNNdGwthyYEp4Axl5o6x3JaEvIBmpx846523tn1N5aXomcghVWwyjZcu0zIJgELyzhQT6ogXSijG7PBrCOvebuhIFz/xC7qS+OW5DXdQ/tlU1Kv9peC+hoyv3ANvHPhspd0TpCRHFJZ2+W2WY8rhWSM9S/GqG8BQnD3gfIQATB/K613CtMkMHH/n0lI4CxNImxo+YUsLALmDWiC3baBHklpUsg1Q7Uv2subJhK5PO66btL6aUtLv8XGFaMU6xbezib6y2e8YR6LUiXK1/yXGa3joiD7gANT0IY6hnrp+dqxcnAhFhnoCKNY0Sf/DTcwrCa3w8sIkV5fc7KgGD9OEi9hL/7hvV4w5MRREi10aMXPTAaRFj+R4zfMxNHqKdDS3Z/mT92i3zSHOE5BrTe7AYp1fxrmsOuSZDnfmwFmtEwm7p20d1gv1uUunJIsxnJigkhef+bjdvHs4nf4KRs7Njm2V9ZGjRDpEoVJ4/LKrtJQM9eL3KvOAQarCpLdgN/8hMqTD2JupBk/LXAy6NVINAnfehOFuhNE0kkDOYy73Bx2bIrbrpqUf5s64ZofhmmMreR/Ej0QUiLTJNyiG23vq0H7Y/mi8sMH4i38VAwYjXVEvudA2fflB2aRDNuYWSj420nD/Dl/AGpGdwPR+7flRLNkE="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "GhiMQTli8zhcGAH7IIH1gvrKS1cUn5V/u8VphHBiTGS9RHCOcZ1lSTIG2rSPHjoI1uR8KgqLq4JCJ1nBCLNk7GbawJSv5Ke7rUgYCeLHVByYKBGNLoi7Fbpz6Buaw/xA8VSJvzsqQ0mYNz/oNOqcJwWXTRausUrqKL02qeAGLVDZl0a4R4rOk66syaAXuCT1U7k7nqpP2oc7eL0lSMdbTlsBewMOrobSB5tbj0EKWwKJsplknNqagnLA3u+b5KoupsUdz8mfoqwDwtLfWfpro9Fv6ln1MpuwtT8toXr6NVemSL7FNqjgr5rDGHX0oClEqfk7FSpmNIBkuz79VNMU0vMEZx3/DwfZKL/gQ0jieIKyfIIWPgWIEauu7LsFpo9Az3nb+5eyu1C0ZLVBg4RhEX6DLWsIHbshPHG3QKaF+B7FKzIchvlK156MKAob4/KxKM9NrLQ4JDI88I3gc89G3NosV4HM6V79jPEoqJINzX+6sVcYGINOzYO9krXDyCEHkwNd9bMoXZ3sKV30g0qgNCVMTj4nc42wz0BWWjnCJnNrqL05wr9zTQbVUt2yqRxulkM9JBjRSHuQnOkLgA1rzsYf2J0Uj6OcqOr4c4ehh1Q7DT6Gl8EHKXK4ZHD0uEt//LMkgSpWwjeUZ5DOvvDYyHPbvEzYS5scY9sLQz1qWwQ="
    on:
      tags: true
    skip_cleanup: true
